### ISSUE TITLE
ckan metadata importer

### ISSUE THREAD

**Issue by max-mapper** [datproject/svalbard#1]
to support this would be nice to have a thing that can import all ckan metadata from a ckan instance on some regular interval. later we can do a full content mirror based on this metadata archive

- [ ] figure out how to best model the metadata in a dat archive (e.g. a series of files or maybe a hypercore stream)
- [x] run it for http://catalog.data.gov/api/3/action/package_search

**Comment by max-mapper** [comment]
I did this last night! Except haven't put it into Dat yet

**Comment by okdistribute** [comment]
awesome! 

would love to have this one in a dat: http://publicdata.eu/

**Comment by okdistribute** [comment]
let me know when you have a prototype and i'll be happy to hack on it too!
